### ISSUE TITLE
FileBeat Not Starting Inside the Container

### ISSUE THREAD

**Issue by neeldeep** [burakince/aspnetcore-supervisor-filebeat-example#1]
Cloned the repository and started the container but FileBeat doesn't seem to be starting automatically.
I had to log into the container and start FileBeat manually using the following command:
`service filebeat start`
I am also trying to start FileBeat using supervisord in a dot net core microservice, not sure if it has something to do with FileBeat

**Comment by burakince** [comment]
Please run this command. CONTAINER_ID should be your container ID

```
docker exec -it CONTAINER_ID bash
```

After that could you send me this command results

```
cat /var/log/supervisord/supervisord.log
```

**Comment by neeldeep** [comment]
root@e85344019c1c:/app# **service filebeat status**        
         
[FAIL] filebeat is not running ... failed!

root@e85344019c1c:/app# **cat /var/log/supervisord/supervisord.log**

2018-04-29 16:37:21,611 CRIT Supervisor running as root (no user in config file)
2018-04-29 16:37:21,615 INFO supervisord started with pid 1
2018-04-29 16:37:22,618 INFO spawned: 'value-service' with pid 8
2018-04-29 16:37:22,620 INFO spawned: 'filebeat' with pid 9
2018-04-29 16:37:24,256 INFO success: value-service entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-04-29 16:37:24,256 INFO success: filebeat entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

Including the log. Even thought the log says filebeat entered into RUNNING it is not running
Check the first line of the log with which I am verifying the status.

**Comment by burakince** [comment]
Filebeat service manages by the Filebeat-god. That means it's a different process. You can not check process like that. You already have a running Filebeat process and it's managing by Superviserd.

When you run the following command you will see 2 different Filebeat processes. One is started by Superviserd and other is started by you.

```
docker top CONTAINER_ID
```

You don't need to use Filebeat service. Filebeat already managing by Superviserd. Please check http://supervisord.org/ documentation.

**Comment by neeldeep** [comment]
Thanks for the clarification. 
However I have another observation, when I am starting the container the Filebeat log folder is not created and no logs are generated here.
"/var/log/filebeat"
But if I start the service using "service filebeat start" the log folder is created and log files are being generated.

**Comment by burakince** [comment]
Because they are writing another directory, which is defined in https://github.com/burakince/aspnetcore-supervisor-filebeat-example/blob/d7e726ee424807750ff28a2370d12dc226857588/supervisord.conf#L4 line. You can find all logs in that directory ( /var/log/value-service ). I strongly recommend you http://supervisord.org/ documentation. Because all process managing by Superviserd in this example.

**Comment by neeldeep** [comment]
I am new to supervisord and going through some of the initial documentation

You are referring to the path from where to read the logs which is defined in your Filebeat yml. I am referring to the folder where Filbeat generates it's own log.

**docker top d7d7d6abe36e**
PID                 USER                TIME                COMMAND
27055               root                0:00                {supervisord} /usr/bin/python /usr/bin/supervisord -c /etc/value-service/supervisord.conf
27083               root                0:00                dotnet /app/ValueService.dll
27084               root                0:00                /usr/share/filebeat/bin/filebeat -path.home /usr/share/filebeat -path.config /etc/filebeat -path.data /var/lib/filebeat -**path.logs /var/log/filebeat -e -c=/etc/filebeat/filebeat.yml**

Check the above information. The log folder for Filebeat is not present when the process is managed by supervisord.

**Comment by burakince** [comment]
Could you send me following command results?

```
ls -al /var/log/value-service
```

**Comment by neeldeep** [comment]
```
root@d7d7d6abe36e:/var/log/value-service# ls -al
total 36
drwxr-xr-x  2 root root  4096 Apr 29 17:29 .
drwxr-xr-x 12 root root  4096 Apr 29 17:29 ..
-rw-------  1 root root 18930 Apr 29 17:30 filebeat-stderr---supervisor-rXfbN1.log
-rw-------  1 root root     0 Apr 29 17:17 filebeat-stdout---supervisor-Hea7GL.log
-rw-------  1 root root     0 Apr 29 17:17 value-service-stderr---supervisor-QOehaY.log
-rw-------  1 root root   665 Apr 29 17:17 value-service-stdout---supervisor-gSIgu2.log
```

**Comment by burakince** [comment]
And could you run following command?

```
service filebeat stop
```

After that could you send me following command results?

```
docker top CONTAINER_ID
```

**Comment by neeldeep** [comment]
```
docker top d7d7d6abe36e
PID                 USER                TIME                COMMAND
27055               root                0:00                {supervisord} /usr/bin/python /usr/bin/supervisord -c /etc/value-service/supervisord.conf
27083               root                0:01                dotnet /app/ValueService.dll
27084               root                0:00                /usr/share/filebeat/bin/filebeat -path.home /usr/share/filebeat -path.config /etc/filebeat -path.data /var/lib/filebeat -path.logs /var/log/filebeat -e -c=/etc/filebeat/filebeat.yml
```

**Comment by burakince** [comment]
Cool! :) We have running filebeat process and it writing all errors to `/var/log/value-service/filebeat-stderr---supervisor-rXfbN1.log` file. Errors make sense in here because in https://github.com/burakince/aspnetcore-supervisor-filebeat-example/blob/d7e726ee424807750ff28a2370d12dc226857588/filebeat.yml#L155 line we defined `localhost:5044` for logstash server but you don't have any logstash server in there. So we can change that line with real logstash server IP address or domain name. After that it should send all logs to logstash.

**Comment by burakince** [comment]
Could you try it and send me results?

**Comment by neeldeep** [comment]
Let me connect it directly to my Elastic Search instance and update the yml file and share the results with you.
Has been fun interacting with you :)

**Comment by neeldeep** [comment]
How do I restart Filebeat running under supervisor if I making a change in the yml file?

**Comment by burakince** [comment]
Don't change any configuration file in the docker containers. It is an antipattern. Just create a new image with your new files and use it. :) It is easier and more manageable way.

**Comment by burakince** [comment]
Also, you can kill filebeat process with `kill` command. Superviserd will create another filebeat process with your new configuration file. But I do not recommend this way.

**Comment by neeldeep** [comment]
```
-rw-------  1 root root 15490 Apr 29 14:12 filebeat-stderr---supervisor-6dzpYx.log
-rw-------  1 root root     0 Apr 29 14:03 filebeat-stdout---supervisor-Z1082w.log
```
When i run the service the "**filebeat-stderr**" seems to be updated and I can see the logs in Elastic Search

It seems to be working now. I added this to my supervisord config file:
`childlogdir=/var/log/micro-service`

I created the DockerFile using the aspnet core base image and included FileBeat as part of the Docker Image.
[Docker FIle](https://github.com/neeldeep/Dot-Net-Core-MicroService-FileBeat/blob/master/MicroserviceTest/Dockerfile)

Also what is your thought in running FileBeat in a different container?

**Comment by burakince** [comment]
You can mount your log directory to host machine and you can read them with Filebeat. In that case, you can install Filebeat on the host machine. Or you can use a different container. But in this case, you don't need to use Superviserd. Because you have just one process in your container.
